---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: config | Copy modules templates into default modules path
  template:
    src: "{{ item }}.module.yml.j2"
    dest: "{{ metricbeat_modules_dir }}/{{ item }}.yml"
  with_items: "{{ metricbeat_enabled_modules | default([]) }}"

- name: config | Configuring Metricbeat
  template:
    src: metricbeat.yml.j2
    dest: "{{ metricbeat_config_dir }}/metricbeat.yml"
  notify: restart metricbeat

- name: service | Ensuring Metricbeat Service Is Enabled and Starts On Boot
  service:
    name: metricbeat
    enabled: true
  register: metricbeat_is_running