---
- name: RedHat | Add rpm key for elastic.co
  rpm_key:
    key: "{{ metricbeat_repo_key }}"

- name: RedHat | Create Elasticsearch yum repo
  yum_repository:
    name: elasticsearch
    description: "Metricbeat {{ metricbeat_major_version }}"
    baseurl: "{{ metricbeat_repo_url }}/packages/{{ metricbeat_major_version }}/yum"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ metricbeat_repo_key }}"

- name: RedHat | Install Metricbeat package
  yum:
    name: "{{ metricbeat_package | default(metricbeat_package_default) }}"
    state: present
  notify: restart metricbeat
